controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
    api_login_check:
      path: /api/login_check
    api_refresh_token:
      path: /api/token/refresh
    api_token_invalidate:
      path: /api/token/invalidate
  type: attribute
